function [M,G,K] = BeamRDyn(l,secProp)

% 2-noded (8-DOF) Bernoulli beam element for rotor dynamic for constant
% circular cross section

% (2)------(1)

% degrees of freedom - nodal displacement vector
% u = {w1 theta1 v1 psi1 w2 theta2 v2 psi2}'

% l         ... element length
% secProp   ... Youngs modulus, density, inner radius, outer radius

% M ... mass matrix
% G ... gyroscopic matrix
% K ... stiffness matrix

% Hint: All matrices were generated by the symbolic toolbox!
% (c)by FJ
% -------------------------------------------------------------------------

E   = secProp(1);   % Youngs modulus
rho = secProp(2);   % density
Ri  = secProp(3);   % inner radius
Ra  = secProp(4);   % outer radius

A = (Ra^2-Ri^2)*pi;                 % cross section
I = ((2*Ra)^4-(2*Ri)^4)*pi/64;      % 2nd moment of area
Theta_d = 0.25*rho*A*(Ra^2 - Ri^2); % diametral mass moment of inertia
Theta_p = 0.5*rho*A*(Ra^2 - Ri^2);  % polar mass moment of inertia


%MYFILE
%    Mt = MYFILE(A,L,RHO)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    28-Feb-2022 16:43:27

t2 = l.^2;
t3 = l.^3;
t4 = A.*l.*rho.*(1.3e+1./3.5e+1);
t5 = A.*l.*rho.*(9.0./7.0e+1);
t6 = (A.*rho.*t3)./1.05e+2;
t7 = (A.*rho.*t3)./1.4e+2;
t9 = A.*rho.*t2.*(1.1e+1./2.1e+2);
t10 = A.*rho.*t2.*(1.3e+1./4.2e+2);
t8  = -t7;
t11 = -t9;
t12 = -t10;
Mt  = reshape([t4,t11,0.0,0.0,t5,t10,0.0,0.0,t11,t6,0.0,0.0,t12,t8,0.0,0.0,0.0,0.0,t4,t11,0.0,0.0,t5,t10,0.0,0.0,t11,t6,0.0,0.0,t12,t8,t5,t12,0.0,0.0,t4,t9,0.0,0.0,t10,t8,0.0,0.0,t9,t6,0.0,0.0,0.0,0.0,t5,t12,0.0,0.0,t4,t9,0.0,0.0,t10,t8,0.0,0.0,t9,t6],[8,8]);


%    Mr = MYFILE(Theta_p,L)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    02-Mar-2022 20:18:06

t2 = 1.0./l;
t3 = Theta_p./1.0e+1;
t4 = Theta_p.*l.*(2.0./1.5e+1);
t5 = (Theta_p.*l)./3.0e+1;
t6 = -t3;
t7 = -t5;
t8 = Theta_p.*t2.*(6.0./5.0);
t9 = -t8;
Mr = reshape([t8,t6,0.0,0.0,t9,t6,0.0,0.0,t6,t4,0.0,0.0,t3,t7,0.0,0.0,0.0,0.0,t8,t6,0.0,0.0,t9,t6,0.0,0.0,t6,t4,0.0,0.0,t3,t7,t9,t3,0.0,0.0,t8,t3,0.0,0.0,t6,t7,0.0,0.0,t3,t4,0.0,0.0,0.0,0.0,t9,t3,0.0,0.0,t8,t3,0.0,0.0,t6,t7,0.0,0.0,t3,t4],[8,8]);

M = Mr + Mt;


%    G = MYFILE(Omega,Theta_d,L)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    02-Mar-2022 20:18:54

t2 = 1.0./l;
t3 = (Theta_d)./1.0e+1;
t5 = Theta_d.*l.*(2.0./1.5e+1);
t6 = (Theta_d.*l)./3.0e+1;
t4 = -t3;
t7 = -t5;
t8 = -t6;
t9 = Theta_d.*t2.*(6.0./5.0);
t10 = -t9;
G = reshape([0.0,0.0,t9,t4,0.0,0.0,t10,t4,0.0,0.0,t4,t5,0.0,0.0,t3,t8,t10,t3,0.0,0.0,t9,t3,0.0,0.0,t3,t7,0.0,0.0,t4,t6,0.0,0.0,0.0,0.0,t10,t3,0.0,0.0,t9,t3,0.0,0.0,t4,t8,0.0,0.0,t3,t5,t9,t4,0.0,0.0,t10,t4,0.0,0.0,t3,t6,0.0,0.0,t4,t7,0.0,0.0],[8,8]);


%    K = MYFILE(E,I,L)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    28-Feb-2022 16:47:38

t2 = 1.0./l;
t3 = t2.^2;
t4 = t2.^3;
t5 = E.*I.*t2.*2.0;
t6 = E.*I.*t2.*4.0;
t7 = E.*I.*t3.*6.0;
t9 = E.*I.*t4.*1.2e+1;
t8 = -t7;
t10 = -t9;
K = reshape([t9,t8,0.0,0.0,t10,t8,0.0,0.0,t8,t6,0.0,0.0,t7,t5,0.0,0.0,0.0,0.0,t9,t8,0.0,0.0,t10,t8,0.0,0.0,t8,t6,0.0,0.0,t7,t5,t10,t7,0.0,0.0,t9,t7,0.0,0.0,t8,t5,0.0,0.0,t7,t6,0.0,0.0,0.0,0.0,t10,t7,0.0,0.0,t9,t7,0.0,0.0,t8,t5,0.0,0.0,t7,t6],[8,8]);
